# Generated by Django 5.0 on 2024-10-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
