# Generated by Django 5.0 on 2024-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
