# Generated by Django 5.0 on 2024-10-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_registeruser_delivery_address_registeruser_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
