# Generated by Django 5.0 on 2024-10-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_remove_order_crop_remove_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
