# Generated by Django 5.0 on 2024-10-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
