# Generated by Django 5.0 on 2024-10-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
