# Generated by Django 5.0 on 2024-10-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_delete_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
