# Generated by Django 5.0 on 2024-09-28 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_alter_crop_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
