# Generated by Django 5.0 on 2024-10-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_orderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('name', 'farmer')},
        ),
    ]
