# Generated by Django 5.0 on 2024-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
