# Generated by Django 5.0 on 2024-09-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_crop_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='is_verified',
        ),
    ]
