# Generated by Django 5.0 on 2024-10-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
