# Generated by Django 5.0 on 2024-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_remove_crop_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
