# Generated by Django 5.0 on 2025-01-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('delivery_boy', 'Delivery Boy')], max_length=15),
        ),
        migrations.CreateModel(
            name='DeliveryBoyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('other', 'Other')], max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('area_of_service', models.TextField(blank=True, null=True)),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='delivery_docs/')),
                ('completed_registration', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='farm.registeruser')),
            ],
        ),
    ]
