# Generated by Django 5.0 on 2025-01-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_alter_registeruser_role_deliveryboydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
