# Generated by Django 5.0 on 2025-01-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_registeruser_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoyDetail',
        ),
    ]
