# Generated by Django 5.0 on 2024-10-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_cart_added_at_alter_cart_crop_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
