# Generated by Django 5.0 on 2024-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
