# Generated by Django 5.0 on 2025-01-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_deliveryboydetail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
