# Generated by Django 5.0 on 2025-01-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_order_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
