# Generated by Django 5.0 on 2024-10-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_registeruser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='last_login',
        ),
    ]
