# Generated by Django 5.0 on 2024-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0032_remove_registeruser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
