# Generated by Django 5.0 on 2025-02-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_category_alter_crop_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='crop',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='cropimage',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='deliveryboydetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_delivery_boy',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='CropImage',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='DeliveryBoyDetail',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
