# Generated by Django 5.0 on 2025-02-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0035_category_crop_cropimage_deliveryboydetail_feedback_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('name', 'farmer', 'subcategory')},
        ),
    ]
