# Generated by Django 5.0 on 2025-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0036_alter_crop_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
