# Generated by Django 5.0 on 2025-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0037_alter_crop_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboydetail',
            name='current_orders',
            field=models.IntegerField(default=0),
        ),
    ]
