# Generated by Django 5.0 on 2025-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0039_order_is_canceled_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
