# Generated by Django 5.0 on 2025-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0040_order_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboydetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboydetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
