# Generated by Django 5.0 on 2025-03-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0044_bulkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.registeruser'),
        ),
    ]
