# Generated by Django 5.0 on 2025-03-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0045_alter_bulkorder_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Payment Pending', 'Payment Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
