# Generated by Django 5.0 on 2025-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0046_bulkorder_is_paid_bulkorder_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
