# Generated by Django 5.0 on 2025-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0047_bulkorder_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
